### ISSUE TITLE
Issue with the order of groovy scripts execution

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#116]
There is seems to be a dependency between scripts. For instance artifactory script expects to find credentials that are generated by credentials groovy script which get executed after only after artifactory.

We need to figure out a good solution how to ensure the order of execution of the scripts. Currently, it is based on the script names and sorted alphabetically.

Introduce numbering?

**Comment by ewelinawilkosz2** [comment]
will be handled in plugin reposotory: https://github.com/Praqma/system-config-dsl-plugin/issues/11
