### ISSUE TITLE
Prepare proposal for detaching configuration from global settings

### ISSUE THREAD

**Issue by ewelinawilkosz2** [Praqma/JenkinsAsCodeReference#183]
Customer's/user's specific configuration should be kept separately from global config/features
Before starting implementation the proposal has to review by more people involved in the project

The goal here is to create a nice workflow that will encourage people to implement solutions in this repository and the pull it back into their forks without complicated merge conflicts when specific configuration e.g. for the plugins which will be supported in this repository will be kept in separate repository

**Comment by Andrey9kin** [comment]
@ewelinawilkosz2 it probably makes sense to look into this plugin https://github.com/jenkinsci/system-config-dsl-plugin/blob/master/README.md started by Kohsuke but never finished and released. We could take over and contribute what we already did to this plugin. In this way, configuration scripts will be delivered via plugin

Also, I suggest we announce our intentions here https://issues.jenkins-ci.org/browse/JENKINS-31094 and see if more people want to join

**Comment by ewelinawilkosz2** [comment]
our intentions are now announced and we've decided to go with the plugin. Documentation will be available at https://github.com/Praqma/system-config-dsl-plugin
