### ISSUE TITLE
Add possibility to specify slave labels for the job

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#2]
DoD: Provide possibility to set node labels for the jobs, update current jobs to pick linux slave, add labels to the existing slave (linux, docker).

**Comment by alexsedova** [comment]
Question: How we will define which label will be assign to which node? Should I get first node and set linux , get second and set docker, etc. , or ... You now have possibility to rename and assign... manually))) If we want to assign labels during start up, what the order will be ?

**Comment by Andrey9kin** [comment]
@alexsedova we will have to specify such info during slave build process. This setup has only one node, and we should set labels in the start.sh. The same have to be done for any other slave that will be created later on, i.e. slave build file (Docker/Packer/whatever) will contain predefined labels
