### ISSUE TITLE
master image build stops when downloading plugins

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/JenkinsAsCodeReference#203]
may be firewall related

**Comment by drBosse** [comment]
We can close this

When global DNS is blocked in corporate networks
Add the corporate DNS to the docker daemon

From: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
/etc/docker/daemon.json:

{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
