### ISSUE TITLE
Add jenkins/slave version info as env variable

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#3]
Set env variable inside a container to point out image version. Variable name DOCKER_IMAGE_VERSION. Should contain image name together with its version

Intended use is as a part of build info for artifacts

DoD:

- image info presented as env variable inside the container
- slave image name and version is stated in the slave name and as a slave label
- master image name and version is shown on the front page (Manage Jenkins -> Global Configuration -> Config)

**Comment by Andrey9kin** [comment]
Set env variable inside container to point out image version. Variable name JENKINS_IMAGE_VERSION. Should contain image name together with its version

**Comment by alexsedova** [comment]
I've made changes for muchhausen docker-compose. Is it make a sense to do changes for original code master and slave? As I understood we will pull docker images from the repo, that will do pipeline, and from pipeline we will take label. If so I'm ready to commit. If not - need to discuss))
