### ISSUE TITLE
Experimental: Implement review job as a pipeline

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#43]
Required for #34 since pipelines have a better support for reading env variables

**Comment by Andrey9kin** [comment]
Waiting for help from Thierry to fix pretested so it could be called from the pipeline
On hold

**Comment by ewelinawilkosz2** [comment]
@praqma-thi it's pretty old but I'm going through all the tickets to verify if those are still valid - do you know what was the problem with pretested? and if it's fixed?

**Comment by praqma-thi** [comment]
PIP is still incompatible with pipeline, some politics involved.
We'll fix it in the upcoming codecamp.
https://trello.com/c/8IJYjZ6C

**Comment by ewelinawilkosz2** [comment]
will remove review job (probably)'or we can keep it as a template - decision has to be made

**Comment by ewelinawilkosz2** [comment]
we're removing the job
