### ISSUE TITLE
Support for docker pipeline plugin

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#84]
In order to support pushes to secure registries, i.e. we need to have a good way to login to the registry

https://github.com/jenkinsci/docker-workflow-plugin/blob/master/demo/README.md

**Comment by alexsedova** [comment]
If I correct investigated the issue, docker-workflow plugin just provide DSL to use it in pipeline scripts. We don't need configure anything in global jenkins configuration. Only one change we really need. In according https://issues.jenkins-ci.org/browse/JENKINS-35217 we have to mount workspace additionally.

**Comment by alexsedova** [comment]
Authentication to registry: "To select a custom registry, wrap build steps which need it in the withRegistry method on docker (inside node if you want to specify a slave explicitly). You should pass in a registry URL. If the registry requires authentication, you can add the ID of username/password credentials. (Credentials link in the Jenkins index page or in a folder; when creating the credentials, use the Advanced section to specify a memorable ID for use in your pipelines.)" See: https://go.cloudbees.com/docs/cloudbees-documentation/cje-user-guide/chapter-docker-workflow.html
